baseURL = "https://savakarrohan.github.io/website/"
languageCode = "en-us"
title = "Savakar Rohan's site"
theme = "Bootstrap_01"








# To not escape all html in markdown.
[markup.goldmark.renderer]
    unsafe= true